package(default_visibility = ["//visibility:public"])

py_library(
    name = "array_io_utils",
    srcs = ["array_io_utils.py"],
)

py_library(
    name = "runfile_utils",
    srcs = ["runfile_utils.py"],
    deps = [
        "@bazel_tools//tools/python/runfiles",
    ],
)
