name: PyLinter

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  # Run Pylinter formatter
  pylinter:
    name: Format code base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Run Pylint formatting
      - name: GitHub Action for pylint
        uses: cclauss/GitHub-Action-for-pylint@0.7.0
        with:
            args: "pip install -r $GITHUB_WORKSPACE/requirements.txt ; pylint **/*.py"
