name: Super-Linter

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  
  # Run SuperLint code stability check
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Super-Linter
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Run Pylint formatting
  linting:
    name: PyLint
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip3 install -U pip setuptools
      - run: pip3 install -U -r requirements.txt
      - run: pylint --rcfile=.pylintrc src/
